#ifndef _image_defs_h_
#define _image_defs_h_


// some of this defines are made for YUV420 but we are nit yet there... be careful

#define JPEG_SWAP_BUFFER            2000
#define JPEG_WEB_BUFFER             JPEG_SWAP_BUFFER

#define LINES_IN_FRAME_SubQCIF      96
#define LINES_IN_FRAME_QCIF         144
#define LINES_IN_FRAME_CIF          288
#define LINES_IN_FRAME_QQVGA        120
#define LINES_IN_FRAME_QVGA         240
#define LINES_IN_FRAME_VGA          480
#define LINES_IN_FRAME              LINES_IN_FRAME_QQVGA

#define PIXELS_IN_LINE_SubQCIF      128
#define PIXELS_IN_LINE_QCIF         176
#define PIXELS_IN_LINE_CIF          352
#define PIXELS_IN_LINE_QQVGA        160
#define PIXELS_IN_LINE_QVGA         320
#define PIXELS_IN_LINE_VGA          640
#define PIXELS_IN_LINE              PIXELS_IN_LINE_QQVGA
#define Y_VALUES_IN_LINE            PIXELS_IN_LINE
#define U_VALUES_IN_LINE            PIXELS_IN_LINE/2
#define V_VALUES_IN_LINE            U_VALUES_IN_LINE

#define MIN_YUV422_SubQCIF         4096
#define MIN_YUV422_QCIF            5632
#define MIN_YUV422_CIF             11264
#define MIN_YUV422_QQVGA           5120
#define MIN_YUV422_QVGA            10240
#define MIN_YUV422_VGA             20480
#define MIN_YUV422_PACKET_SIZE     MIN_YUV422_QQVGA

#define MIN_YUV420_SubQCIF         3072
#define MIN_YUV420_QCIF            4224
#define MIN_YUV420_CIF             8448
#define MIN_YUV420_QQVGA           3840
#define MIN_YUV420_QVGA            7680
#define MIN_YUV420_VGA             15360
#define MIN_YUV420_PACKET_SIZE     MIN_YUV420_QQVGA

#define N_PACKETS_FRAME_SubQCIF     6
#define N_PACKETS_FRAME_QCIF        9
#define N_PACKETS_FRAME_CIF         18
#define N_PACKETS_FRAME_QQVGA       7               // 7.5   I am not positive how to proceed here
#define N_PACKETS_FRAME_QVGA        15
#define N_PACKETS_FRAME_VGA         30
#define N_PACKETS_IN_FRAME          N_PACKETS_FRAME_QQVGA

#define Y_YUV420_DATA_SIZE_SubQCIF      MIN_YUV422_SubQCIF/2
#define Y_YUV420_DATA_SIZE_QCIF         MIN_YUV422_QCIF/2
#define Y_YUV420_DATA_SIZE_CIF          MIN_YUV422_CIF/2
#define Y_YUV420_DATA_SIZE_QQVGA        MIN_YUV422_QQVGA/2
#define Y_YUV420_DATA_SIZE_QVGA         MIN_YUV422_QVGA/2
#define Y_YUV420_DATA_SIZE_VGA          MIN_YUV422_VGA/2

#define U_YUV420_DATA_SIZE_SubQCIF      Y_YUV420_DATA_SIZE_SubQCIF/4
#define U_YUV420_DATA_SIZE_QCIF         Y_YUV420_DATA_SIZE_QCIF/4
#define U_YUV420_DATA_SIZE_CIF          Y_YUV420_DATA_SIZE_CIF/4
#define U_YUV420_DATA_SIZE_QQVGA        Y_YUV420_DATA_SIZE_QQVGA/4
#define U_YUV420_DATA_SIZE_QVGA         Y_YUV420_DATA_SIZE_QVGA/4
#define U_YUV420_DATA_SIZE_VGA          Y_YUV420_DATA_SIZE_VGA/4

#define U_INDEX_YUV420_PLANAR_SubQCIF   Y_YUV420_DATA_SIZE_SubQCIF
#define U_INDEX_YUV420_PLANAR_QCIF      Y_YUV420_DATA_SIZE_QCIF
#define U_INDEX_YUV420_PLANAR_CIF       Y_YUV420_DATA_SIZE_CIF
#define U_INDEX_YUV420_PLANAR_QQVGA     Y_YUV420_DATA_SIZE_QQVGA
#define U_INDEX_YUV420_PLANAR_QVGA      Y_YUV420_DATA_SIZE_QVGA
#define U_INDEX_YUV420_PLANAR_VGA       Y_YUV420_DATA_SIZE_VGA
#define U_INDEX_YUV420_PLANAR           U_INDEX_YUV420_PLANAR_QQVGA

#define V_INDEX_YUV420_PLANAR_SubQCIF   U_INDEX_YUV420_PLANAR_SubQCIF + U_YUV420_DATA_SIZE_SubQCIF
#define V_INDEX_YUV420_PLANAR_QCIF      U_INDEX_YUV420_PLANAR_QCIF + U_YUV420_DATA_SIZE_QCIF
#define V_INDEX_YUV420_PLANAR_CIF       U_INDEX_YUV420_PLANAR_CIF + U_YUV420_DATA_SIZE_CIF
#define V_INDEX_YUV420_PLANAR_QQVGA     U_INDEX_YUV420_PLANAR_QQVGA + U_YUV420_DATA_SIZE_QQVGA
#define V_INDEX_YUV420_PLANAR_QVGA      U_INDEX_YUV420_PLANAR_QVGA + U_YUV420_DATA_SIZE_QVGA
#define V_INDEX_YUV420_PLANAR_VGA       U_INDEX_YUV420_PLANAR_VGA + U_YUV420_DATA_SIZE_VGA
#define V_INDEX_YUV420_PLANAR           V_INDEX_YUV420_PLANAR_QQVGA

//#define JPEG_BLOCKS_IN_LINE_SubQCIF     PIXELS_IN_LINE_SubQCIF/8
//#define JPEG_BLOCKS_IN_LINE_QCIF        PIXELS_IN_LINE_QCIF/8
//#define JPEG_BLOCKS_IN_LINE_CIF         PIXELS_IN_LINE_CIF/8
//#define JPEG_BLOCKS_IN_LINE_QQVGA       PIXELS_IN_LINE_QQVGA/8
//#define JPEG_BLOCKS_IN_LINE_QVGA        PIXELS_IN_LINE_QVGA/8
//#define JPEG_BLOCKS_IN_LINE_VGA         PIXELS_IN_LINE_VGA/8
//#define JPEG_BLOCKS_IN_LINE             JPEG_BLOCKS_IN_LINE_QVGA

#endif
